version: '3.8'
services:
  postgres:
    image: postgres:17 
    container_name: dice_master_service
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:  
      test: ["CMD-SHELL", "pg_isready -U user -d db"]
      interval: 10s
      retries: 5
      timeout: 5s

  app:
    build: .
    container_name: dice_master_app
    restart: always
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy 
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    command: npm run start:dev

volumes:
  pg_data:
